/** @deprecated Import from `@/lib/game/bughouse-engine` instead. */
export {
  addCaptured,
  applyDrop,
  applyMove,
  BOARD_IDS,
  BOARD_TEAM_MAP,
  canDropPiece,
  consumeCaptured,
  createBoard,
  createInitialSnapshot,
  DROP_PIECES,
  evaluateMatchEnd,
  formatDropNotation,
  getCapturedPieceType,
  getInitialFen,
  getPartnerSeatId,
  getPhysicalBoard,
  getSeatColor,
  getTeamForColorOnBoard,
  getTimeForfeitTeam,
  getValidDropSquares,
  getWinnerTeamFromBoards,
  isGameOver,
  isValidDrop,
  normalizeCaptured,
  parseDropNotation,
  reservePieceFromCapture,
  SEAT_CONFIG,
  type BoardId,
  type BoardSeatId,
  type PieceSymbol,
} from "./bughouse-engine";
